# Generated by Django 4.1.7 on 2024-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_disaster_isactive_disaster_reporttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='isassigned',
            field=models.BooleanField(default=False),
        ),
    ]
