# Generated by Django 4.1.7 on 2024-02-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0003_volunteer_isassigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerAssginment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disaster')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.volunteer')),
            ],
        ),
    ]
