# Generated by Django 4.1.7 on 2024-02-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0004_volunteerassginment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disaster')),
            ],
        ),
    ]
