# Generated by Django 4.1.7 on 2024-04-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0008_contributor_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='bussness',
            new_name='business',
        ),
    ]
