# Generated by Django 4.1.7 on 2024-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0009_rename_bussness_contributor_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='ip_proof',
            new_name='id_proof',
        ),
    ]
