# Generated by Django 4.1.7 on 2024-04-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0010_rename_ip_proof_contributor_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAlloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disaster')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.resource')),
            ],
        ),
        migrations.AddField(
            model_name='disaster',
            name='resources',
            field=models.ManyToManyField(related_name='disaster_resources', through='disaster.ResourceAlloc', to='disaster.resource'),
        ),
    ]
